---
- name: create a windows user
  hosts: windows10
  tasks:
    - name: create windows user
      win_user:
        name: sainaung
        password: Pa$$w0rd
        state: present
        groups:
          - Users
