---
# tasks file for myvhost

- name: Ensure httpd is installed
  yum:
    name: httpd
    state:  latest

- name: Ensure httpd is started and enabled
  service:
    name: httpd
    state: started 
    enabled:  true

- name: vhost is installed
  template: 
    src:  vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner:  root
    group:  root
    mode: 0644

- name:  Create Vhost Document Root
  file:
     path: /var/www/vhosts/servera/
     state: directory
 
- name: enable http service
  firewalld:
    service:  http
    permanent:  yes
    immediate:  yes
    state:  enabled
  notify:
    - restart httpd
