---
- name: Enable intranet services
  hosts: servera.lab.example.com
  become: true
  tasks:
    - name: installed latest version of httpd and firewalld
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - httpd
          - firewalld
        state: latest

    - name: test html page is installed
      copy:
        content:  "Welcome to the intranet !\n"
        dest: /var/www/html/index.html

    - name: firewalld enabled and running
      service:  
        name: firewalld
        state: started
        enabled: true

    - name: firewalld permits access to httpd service
      firewalld:
        service:  http
        permanent: yes
        state: enabled
        immediate: yes

    - name: httpd enabled and running 
      service:
        name: httpd
        state:  started
        enabled: true


- name:  Test the intranet web server
  hosts: localhost
  become: no
  tasks:
    - name: connect to intranet web server
      uri:
        url:  http://servera.lab.example.com
        return_content: yes
        status_code: 200