---
- name: Update Web server
  hosts:  webservers
  become: true
  serial: 3

  tasks:  
    - name: Latest httpd package installed
      yum:  
         name: httpd
         state:  latest
      notify:
          - Restart httpd

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
        enabled: true
